changelog:
  exclude:
    labels:
      - "skip-changelog"
    authors:
      - "dependabot[bot]"
  categories:
    - title: "New Features"
      labels:
        - "feature"
    - title: "Bug Fixes"
      labels:
        - "bug"
    - title: "Other Changes"
      labels:
        - "*"
