image:
  repository: <acr-name>
  name: contoso-website
  tag: latest
  version: 0.0.1

dns:
  name: <your-dns-zone-name>

readiness_probe:
  enabled:

basic_auth:
  enabled: 
  
wprowadzam_zmiane_na_stage:
  a_ona_powinna_byc_na_main: sad_face
