name: Release actions

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        run: |
          echo tag_name: ${{ github.ref }}
          echo tag_name number: ${GITHUB_REF##*/}
          echo tag_name: ${{ github.tag_name }}
          echo "GitHub environment: ${{ toJson(github) }}"
