  
name: Commit from Github Action

on:
  workflow_dispatch

jobs:
  commit_from_ga:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set env
      run: echo RAND=$( echo "asdf"$RANDOM ) >> $GITHUB_ENV
    #- name: Create local changes
    #  run: |
    #    touch $RAND
    - name: Set Helm Chart versions
      run: |
        sed -i "s/^version:.*$/version: 0.1.0/" kubernetes/contoso-website/Chart.yaml
        sed -i "s/^appVersion:.*$/appVersion: 0.2.2/" kubernetes/contoso-website/Chart.yaml
    - name: Commit files
      run: |
        git config --local user.email "adamerot[at]hotmail.com"
        git config --local user.name "aerott"
        git add .
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
