  
name: Get tags

on:
  workflow_dispatch

jobs:
  get_tags:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
          
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      
      # output:
      # >> Found tag: v1.0.3
      # >> Found timestamp: 1616149886
        
      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

