  
name: Notification to MS Teams (other)

on:
  workflow_dispatch

jobs:
  send_notification:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Get Last Commit Changes
        id: commit_changes
        run: |
          git fetch
          LAST_COMMIT_HASH=$(git rev-parse HEAD)
          COMMIT_CHANGES=$(git log -1 --pretty=format:"%s" $LAST_COMMIT_HASH)
          COMMIT_LINK="https://github.com/${{ github.repository }}/commit/${LAST_COMMIT_HASH}"
          echo "commit_changes=${COMMIT_CHANGES}" >> $GITHUB_OUTPUT
          echo "commit_link=${COMMIT_LINK}" >> $GITHUB_OUTPUT

      - name: Display Last Commit Changes
        run: |
          echo "Last commit changes: ${{ steps.commit_changes.outputs.commit_changes }}"
          echo "View commit changes: ${{ steps.commit_changes.outputs.commit_link }}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: | 
          echo "$GITHUB_CONTEXT"
          echo tag_name: ${{ github.ref }}
          echo tag_name number: ${GITHUB_REF##*/}
          echo "Job URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Send notification to MS Teams channel
        #uses: rfuehrer/actions.webhook-to-ms-teams@1.0
        uses: admteam-shock-it/actions.webhook-to-ms-teams@0.1.0
        with:
          webhook: https://shockitsoft.webhook.office.com/webhookb2/1b531eb4-02eb-49f5-8b39-f99930a70861@3fda335c-e186-4ee4-94ed-15774c335171/IncomingWebhook/ae7c66150c914706b6e14ec8411709e1/7a8908b8-d686-4b88-88fd-8fa991aeec38
          message: '<h1>&#x1F6A2;${{github.workflow}} has been finished successfully! &#x2705; &#x1F60A;</h1><br><b>Repository</b>: <a href=${{github.event.repository.html_url}}>${{github.repository}}</a><br>Branch: <b>${GITHUB_REF##*/}</b><br>ImageTag: <b>${{ github.ref }}</b><br><br>Commit changes name: <b>${{ steps.commit_changes.outputs.commit_changes }}</b><br>View commit changes: <a href=${{ steps.commit_changes.outputs.commit_link }}>${{ steps.commit_changes.outputs.commit_link }}</a><br><br>Workflow job: <a href=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}>https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}</a><br><br><b>Stay tuned!</b><br>'
      
