
name: Steps Test

on:
  workflow_dispatch

env:
  TAG_TEST:         1.0.2

  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=tags::${{ env.TAG_TEST }}
          
      - name: Test variable
        run: |
          echo ${{ steps.prep.outputs.tags }}

  deploy:
    runs-on: ubuntu-20.04
    needs: build
    
    steps:
      - uses: actions/checkout@v2

      - name: Test variable from other job
        run: |
          echo ${{needs.build.outputs.tags}}
      
      
