
name: Substraction

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch

env:
  # build stage
  #DEFAULT_IMAGE_TAG:    test
  APPSETTINGS_PATH:     appsettings.json
  CONNECTION_STRING:    "this-is-connstr"
  SERILOG_DSN:          "this-is-serilog-dsn"
  
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      
      - name: Variable substitution
        uses: admteam-shock-it/variable-substitution@7 #beta-6
        with:
          files: ${{ env.APPSETTINGS_PATH }}
        env:
          #ConnectionStrings.DefaultConnection: "asdf"
          ConnectionStrings.DefaultConnection:  ${{ env.CONNECTION_STRING }}
          #PredefinedTags.Tags.0.value: ${{ env.CONNECTION_STRING }}
          Serilog.WriteTo.2.Args.Dsn: ${{ env.SERILOG_DSN }}
          # previous appsettings
          #Serilog.WriteTo.1.Args.Dsn: ${{ env.SERILOG_DSN }}
          IdentityServer.Clients.0.RedirectUris: '["url1","url2"]'
          This.Env: "not exists in appsettings.json"
          
      - name: Prepare
        id: prep
        run: |
          cat appsettings.json


