
name: Manual triggers with workflow_dispatch

on: 
  workflow_dispatch:
    inputs:
      tags:
        required: true
        description: 'Input branch name'
env:
  test: github.event.inputs.tag
jobs:
  init_job:
    runs-on: ubuntu-20.04
    outputs:
      val1: ${{ steps.setvars.outputs.val1 }}
      val2: ${{ steps.setvars.outputs.val2 }}
      
    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ ${{ env.test }} == "develop" ]]; then
            echo "::set-output name=val1::val_develop"
          fi
          
          if [[ "${{github.event.inputs.tag}}" == "main" ]]; then
            echo "::set-output name=val1::val_main"
          fi
          
          if [[ "${{github.event.inputs.tag}}" != "develop" || "${{github.event.inputs.tag}}" != "main" ]]; then
            echo "::set-output name=val1::val_undefined"
          fi
          
  main_job:
    runs-on: ubuntu-20.04
    needs: init_job
    
    steps:
      - name: Log level & Tags
        run: |
          echo "Tags: ${{ github.event.inputs.tags }}" 
          
      - name: Print
        run: echo "val1=${{needs.init_job.outputs.val1}}"   
      
      #- name: Run condition 1
      #  if: github.event.inputs.tags == 'develop'
      #  run: |
      #    echo "You've been wrote - develop"
      #    echo "ref is equal ${GITHUB_REF##*/}"
      #    echo "$GITHUB_CONTEXT"
        
      #- name: Run condition 2
      #  if: github.event.inputs.tags == 'main'
      #  run: |
      #    echo "You've been wrote - develop"
      #    echo "ref is equal ${GITHUB_REF##*/}"
      #    echo "$GITHUB_CONTEXT"
        
      #- name: Run condition 2
      #  if: github.event.inputs.tags != 'develop' && github.event.inputs.tags != 'develop'
      #  run: |
      #    echo "You've been wrote - ?"
      #    echo "ref is equal ${GITHUB_REF##*/}"
      #    echo "$GITHUB_CONTEXT"
