
name: Manual triggers with workflow_dispatch

on: 
  workflow_dispatch:
    inputs:
      confirm1:
        description: 'Insert branch name'     
        required: true
      confirm2:
        description: 'Reinsert branch name'
        required: true
        
jobs:
  init_job:
    runs-on: ubuntu-20.04
    outputs:
      val1: ${{ steps.setvars.outputs.val1 }}
      val2: ${{ steps.setvars.outputs.val2 }}
      
    steps:
      - name: Set variables
        id: setvars
        run: |
          if [[ "${{ github.event.inputs.confirm1 }}" == "develop" ]]; 
          then
            echo "::set-output name=val1::val_develop"
            echo "::set-output name=val2::val_develop"
          elif    
          if [[ "${{ github.event.inputs.confirm1 }}" == "main" ]]; 
          then
            echo "::set-output name=val1::val_main"
          elif      
          if [[ "${{ github.event.inputs.confirm1 }}" != "develop" || "${{ github.event.inputs.confirm1 }}" != "main" ]]; 
          then
            echo "::set-output name=val1::val_undefined"
          fi
          
          echo "aaa: ${{ github.event.inputs.confirm1}}"
          echo "bbbb: ${{ github.event.inputs.confirm2 }}"
          
  main_job:
    runs-on: ubuntu-20.04
    needs: init_job
    
    steps:
      - name: Log level & Tags
        run: |
          echo "Tags: ${{ github.event.inputs.tags }}" 
          
      - name: Print
        run: | 
          echo "val1=${{needs.init_job.outputs.val1}}"
          echo "val2=${{needs.init_job.outputs.val2}}" 
      
      #- name: Run condition 1
      #  if: github.event.inputs.tags == 'develop'
      #  run: |
      #    echo "You've been wrote - develop"
      #    echo "ref is equal ${GITHUB_REF##*/}"
      #    echo "$GITHUB_CONTEXT"
        
      #- name: Run condition 2
      #  if: github.event.inputs.tags == 'main'
      #  run: |
      #    echo "You've been wrote - develop"
      #    echo "ref is equal ${GITHUB_REF##*/}"
      #    echo "$GITHUB_CONTEXT"
        
      #- name: Run condition 2
      #  if: github.event.inputs.tags != 'develop' && github.event.inputs.tags != 'develop'
      #  run: |
      #    echo "You've been wrote - ?"
      #    echo "ref is equal ${GITHUB_REF##*/}"
      #    echo "$GITHUB_CONTEXT"
