
name: Manual triggers with workflow_dispatch

on: 
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Insert branch name'     
        required: true

        
jobs:
  init_job:
    runs-on: ubuntu-20.04
    outputs:
      choosed_branch: ${{ steps.setvars.outputs.choosed_branch }}
      confirm: ${{ steps.setvars.outputs.confirm }}
      
    steps:
      - name: Set variables
        id: setvars
        run: |
          echo BRANCH=${GITHUB_REF##*/}
          if [[ "${{ github.event.inputs.confirm }}" == $BRANCH && "${{ github.event.inputs.confirm }}" == "develop" ]]; 
          then
            echo "1"
            echo "::set-output name=confirm::val_develop"
            echo "::set-output name=choosed_branch::${GITHUB_REF##*/}"   
          elif [[ "${{ github.event.inputs.confirm }}" == "$BRANCH" && "${{ github.event.inputs.confirm }}" == "main" ]]; 
          then
            echo "::set-output name=confirm::val_main"              
          elif [[ "${{ github.event.inputs.confirm }}" == "$BRANCH" && "${{ github.event.inputs.confirm }}" == "stage" ]]; 
          then
            echo "::set-output name=confirm::val_stage"
          else
            echo "::set-output name=confirm::fck_it"
          fi
          
          echo "aaa: ${{ github.event.inputs.confirm }}"
          
  main_job:
    runs-on: ubuntu-20.04
    needs: init_job
    
    steps:
      - name: Choosed Branch & Confirm
        run: |
          echo "Confirm: ${{ github.event.inputs.confirm }}"
          echo "Choosed branch: ${GITHUB_REF##*/}"
          
      - name: Print
        run: | 
          echo "choosed_branch=${{ needs.init_job.outputs.choosed_branch }}"
          echo "confirm=${{ needs.init_job.outputs.confirm }}" 
      
      #- name: Run condition 1
      #  if: github.event.inputs.tags == 'develop'
      #  run: |
      #    echo "You've been wrote - develop"
      #    echo "ref is equal ${GITHUB_REF##*/}"
      #    echo "$GITHUB_CONTEXT"
        
      #- name: Run condition 2
      #  if: github.event.inputs.tags == 'main'
      #  run: |
      #    echo "You've been wrote - develop"
      #    echo "ref is equal ${GITHUB_REF##*/}"
      #    echo "$GITHUB_CONTEXT"
        
      #- name: Run condition 2
      #  if: github.event.inputs.tags != 'develop' && github.event.inputs.tags != 'develop'
      #  run: |
      #    echo "You've been wrote - ?"
      #    echo "ref is equal ${GITHUB_REF##*/}"
      #    echo "$GITHUB_CONTEXT"
